dist: bionic

language: cpp

compiler:
  - clang
  - gcc

script:
- git submodule update --init --recursive
- cmake --version
- mkdir build && cd build
- cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=RELEASE ..
- make
- ./test_unit
- ./test_time
- ./test_inverse_kinematics
